### ISSUE TITLE
Audit schema migrations

### ISSUE THREAD

**Issue by geoo89** [unicef/iogt#1064]
To ensure the migrations don't import/load stuff that might change.

Example: `home/migrations/0026_auto_20211029_1634.py`
Is there a reason it imports `Survey` rather than using `apps.get_model`? If the Survey model changes in the future, the migration might fail.

**Comment by sheralim012** [comment]
The following migrations are causing issues for the new setup from scratch 
- home/0004_auto_20210707_1005.py
- home/0026_auto_20211029_1634.py
- iogt_users/0005_auto_20220120_0813.py
- questionnaires/0010_auto_20210802_1406.py

there are 2 cases that are causing the issues
1 - calling management command
2 - directly accessing models instead of using `app.get_model`

both cause the same issue that is, use the latest version of the model instead of the version during that migration

proposed solution # 1
- instead of calling management command copy refactored management command into migration 
- always use `app.get_model`

proposed solution # 2
- refactor migrations to rip out both cases
- don't reference any model directly or through `app.get_model` in migration 
- always use management commands to fix data

@istride @geoo89 let me know if I missed something

p.s: these changes wouldn't affect existing sites as these migrations are already applied
