### ISSUE TITLE
External links when offline

### ISSUE THREAD

**Issue by geoo89** [unicef/iogt#1146]
Clicking external links when offline currently doesn't work. See #514

**Comment by ChrisMarsh82** [comment]
We need to cache the intermediate page (you are now leaving IoGT) - content to change if online or offline

**Comment by ChrisMarsh82** [comment]
The text should say 'You may not be able to access' - as there is a possibility that they can access the link.

**Comment by ChrisMarsh82** [comment]
Unable to use the intermediate page as it will mean caching all intermediate pages for all links. The solution is to add tooltip/help text next to the link which will be disabled if offline.

**Comment by ChrisMarsh82** [comment]
@cbunicef We can add tooltips on all external links: footer button link, menu button link, link in article body, and link in questionnaire description. Is this ok?

**Comment by cbunicef** [comment]
As discussed there are also possibilities with Markdown blocks to make eg clickable images, etc. Let's get together to discuss.

**Comment by edmoss345** [comment]
Hi @sheralim012 , @geoo89 pointed me to #1275  and I ran a few tests, I'm getting some strange behaviour, not sure if it there is something amiss or there is something wrong with the way I am running things but I will share my results below. 

I set up the manifest as Georg advised and made a few pages to test functionality, I am testing this all in chrome incognito. Georg also advised I comment out the code as below to get things to work in browser?

![image](https://user-images.githubusercontent.com/69303397/173407650-23fb8874-3558-49f6-bad4-8936b6834d9a.png)

First issue I ran into related to the message on the 'Use IoGT offline!' button itself. When I click the button I can see that the download is successful in the dev console. When I switch to 'offline' in the chrome dev console I get the expected result and the  text on the button changes.

![image](https://user-images.githubusercontent.com/69303397/173408085-3cf908fb-dd7b-49dd-bc1b-da53528ecc2a.png)

However, if I remain offline, go to another page then come back then then I am presented with below.

![image](https://user-images.githubusercontent.com/69303397/173408306-cf09f16d-32cd-4af0-8692-ceb1d032b729.png)

Second issue related to the external links, I made a page to test this functionality, it is in a footer and has some external links.

![image](https://user-images.githubusercontent.com/69303397/173408451-34a63727-65cc-4f67-a357-10ce9d31faf4.png)

If I click the button and go into offline mode and then click on the footer button I get the page as below, as I understand it this warning is coming to early as I should only be shown this when trying to see the external link. 

![image](https://user-images.githubusercontent.com/69303397/173409191-5998b6f3-f2c1-40d4-a107-8bc0ee515720.png)

Then confusingly if I go to another section and come back, I am able to access the page with an external link in it, but then I get no warning when I click on the external link itself and just get a standard 'This site can't be reached' page (as you would expect since I'm offline).

Please let me know if that makes sense or if I am doing something fundamentally wrong in my testing, thanks
