### ISSUE TITLE
Make V1PageURLToV2PageMap.v1_page_url a TextField

### ISSUE THREAD

**Issue by geoo89** [unicef/iogt#1172]
Long titles create issues during the V1 Zambia migration, see comments below.

**Comment by cbunicef** [comment]
I'm also fine to cut off the titles, and giving warnings during migration. Whichever is a faster fix.

**Comment by istride** [comment]
To clarify, the problem is related to long titles, but the v1 titles are capped at 255 characters, just like v2. The page titles are a core part of Wagtail and we should not be changing that.

The problem manifests itself when trying to create a `V1PageURLToV2PageMap` during the content migration process. The field `v1_page_url` is capped at 255 characters, but also includes all the section titles leading to the article as well, which, when the article title is at its maximum length, means there is not enough room.

Therefore, I suggest that `V1PageURLToV2PageMap.v1_page_url` needs to be a text field.

**Comment by istride** [comment]
[migration_error_zm.log](https://github.com/unicef/iogt/files/8117623/migration_error_zm.log)
