### ISSUE TITLE
Speed up initial load

### ISSUE THREAD

**Issue by ChrisMarsh82** [unicef/iogt#1184]
Currently, the web page loads slower than V1. see https://www.webpagetest.org/video/compare.php?tests=220223_AiDc5G_DDD,220223_BiDcMX_CY6

**Comment by ChrisMarsh82** [comment]
@sheralim012

**Comment by sheralim012** [comment]
we hit the database for the following cases:
- each translation string (due to patching translation tag of Django)
- each SVG/Raster icon (due to SVG to PNG mapping)
- each button (due to coloring scheme)
- each featured content
- each article (due to coloring scheme and top-level section)
- each section (due to coloring scheme)
- each questionnaire (due to coloring issue)
- each footer (due to linked pages)
- each banner (due to linked pages)

I have created a [PR](https://github.com/unicef/iogt/pull/1193) that solves the following issues
- banner linked pages
- color scheme issue for buttons, article, section, questionnaires

would be better if we can sync on these

**Comment by cbunicef** [comment]
Thanks @sheralim012, these sound like good optimizations in general. 

Do we at the moment think the database responsiveness is a bottleneck?

Would the Django-level caching we have discussed address the items above where there is no obvious solution yet?

**Comment by sheralim012** [comment]
There are a few limitations for Django level caching 
- publishing new content wouldn't take effect immediately (we can decide the time for cache expiration)
- read receipt/content read and similar things wouldn't work

**Comment by cbunicef** [comment]
Thanks, good to know.

Adding some suggestions to the table

| Problem                 | Reason                                                     | Solution                               | Suggestions |
|-------------------------|------------------------------------------------------------|----------------------------------------|---------|
| each translation string | due to patching translation tag of Django                  | Fetch all at once and store in cache                                      | Sufficient to re-cache every 5 mins if there is an update to translation strings, no need for more interactivity |
| each SVG/Raster icon    | due to SVG to PNG mapping                                  | Fetch all at once and store in cache | Needs to be interactive as users are designing as they adding SVGs |
| each button             | due to coloring scheme                                     | Store coloring scheme globally         | |
| each featured content   | due to stream field and each content is fetched separately | -                                      | |
| each article            | due to coloring scheme and top-level section               | Store coloring scheme globally         | |
| each section            | due to coloring scheme                                     | Store coloring scheme globally         | |
| each questionnaire      | due to coloring issue                                      | Store coloring scheme globally         | |
| each footer             | due to linked pages                                        | -                                      | |
| each banner             | due to linked pages                                        | Fetch linked pages with banner page    | Just ensure that this doesn't conflict with hiding published banners if there is no valid link destination |

**Comment by istride** [comment]
@sheralim012 Before embarking on intrusive changes to the app, could we first look for [simple and low-risk interventions][1]?

Adding a Redis cache will not be straightforward because we will have to provision a Redis cluster in production and that will delay the deployment of improvements that require caching with Redis.

I would also like to establish a workflow for measuring performance before and after improvements are made, so that we know what is making a difference and by how much. The alternative is that we blindly make changes without knowing what difference they make and only find out how effective they are once we reach production, which might lead us to waste time.

I would also prefer not to see several improvements bundled into one PR, if it is practical not to do so, as it potentially makes code reviews and debugging more difficult.

[1]: https://www.revsys.com/tidbits/django-performance-simple-things/

**Comment by ChrisMarsh82** [comment]
Use case regarding cache
If an admin user changes either translation, content, or images it would be good if they could see the changes in live straight away. It would make it difficult for content creators to review their work if it always takes 5 minutes for their changes to be seen. 

Could this be done by either setting up certain users not to use the cache or an option that admin could reset the cache? 

@sheralim012 is there anything you can think of we could do to help this use case?

**Comment by cbunicef** [comment]
Thanks @ChrisMarsh82, just to be specific - it's a base requirement that Admin Panel users can see changes made to the front-end live.

We can consider specific exceptions as needed, translation is an example of an exception that is fine for 5-min caching for Admin Panel users as well.

**Comment by geoo89** [comment]
@cbunicef can you elaborate on this?
| Problem                 | Reason                                                     | Solution                               | Suggestions |
|-------------------------|------------------------------------------------------------|----------------------------------------|---------|
| each SVG/Raster icon    | due to SVG to PNG mapping                                  | Fetch all at once and store in cache | Needs to be interactive as users are designing as they adding SVGs |

I don't see any use case where a cache causes issues here. This is a lookup from an (SVG-Image, color) pair to a PNG. Any cache miss (e.g. change the color of a section, or add a new icon somewhere) and a new PNG is generated and the corresponding entry added to the cache.
I don't think users can edit SVGs (which would be the only case I can see where the cache would have to be updated), they can only replace them, which creates a new cache entry.

**Comment by cbunicef** [comment]
Thanks for the response @geoo89. The original idea to cache the icons is from Sher, I just added the "Suggestions" column.

Maybe what I added is better explained as a requirement - that Admin Panel users need to see the changes they make immediately, although a 5-min cache for non-Admin Panel users is fine.

Hope that is more clear?

**Comment by geoo89** [comment]
Yes. I just meant to say that in this particular instance, even if the SVG->PNG cache is never flushed, any kind of changes made to the site would still be instant, as far as I can tell.
This is in particular in response to this commit, which reduces the cache expiry time for the SVG->PNG map, while I don't think it is needed in that case (as explained in my previous comment): https://github.com/unicef/iogt/pull/1193/commits/81e29d21384579f7ebd9fa6342232000ac2283f7

**Comment by sheralim012** [comment]
> Thanks @ChrisMarsh82, just to be specific - it's a base requirement that Admin Panel users can see changes made to the front-end live.

<img width="570" alt="Screenshot 2022-03-11 at 7 11 03 PM" src="https://user-images.githubusercontent.com/49383675/157883951-d8dd7c16-5aa9-4fa7-83c6-0fb8d7c48cd2.png">
using the **preview** button will give user the latest version of page irrespective of being cached (one thing to note is that refreshing the preview page wouldn't work one needs to click on the preview button to get the latest version)

**Comment by cbunicef** [comment]
We do recommend that admins use the Preview button, but this won't completely address the issue. For example, that Preview will still pull from cached versions of other resources (eg embedded Forms, Related Articles, etc).

And just in general, if the Publish action doesn't have any immediate impact on the site for the admin, I do expect there will be confusion.
