### ISSUE TITLE
Revise final data sync before "launch" to keep new users generated since the previous backup

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#1227]
Does the current approach 

1. overwrite the user database in the final data sync? 
2. overwrite the user records that are duplicates?

If it does 1, what is the effort required to convert to 2?

The reason for this is that some colleagues are adding new users in their V2 platform so that they can support on Review and Refine.

If we already have approach 2, or if this will be a non-trivial amount of work, please just close the issue.

**Comment by sheralim012** [comment]
Outlining current approach:

0. delete existing users if the `delete-users` flag is given otherwise don't delete anything
1. if v1 user is already migrated (from the previous sync) then don't do anything with this v1 user
2. if v1 user isn't migrated yet then
    2.1. if v1 username is colliding with the existing v2 username then append `_v2` to v2 username
    2.2. migrate v1 user

I hope this makes sense
Let me know if any change is required

**Comment by cbunicef** [comment]
Thanks @sheralim012, this works. Closing issue.
