### ISSUE TITLE
User-facing survey Pages retain some old settings even after they are changed

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#1257]
To reproduce:

1) Create a new survey
2) Create question 1, radio type, Label: "Test Survey 1 Q 1" Admin Label: "Test Survey 1 Q 1"
3) Publish survey
4) View the following in the user-facing HTML:

```
<div class="quest-item__content">
        <label class="quest-item__label quest-item__input--visible">
          <input type="radio" name="test_survey_1_q_1" value="1" id="id_test_survey_1_q_1_0">
            <span class="cust-check__title">1</span>
        </label>
    </div>
```

5) Edit question 1 to Label: "Test Survey 1 Q 1x" Admin Label: "Test Survey 1 Q 1x"
6) View the following in the user-facing HTML:

```
<div class="quest-item__content">
        <label class="quest-item__label quest-item__input--visible">
          <input type="radio" name="test_survey_1_q_1" value="1" id="id_test_survey_1_q_1_0">
            <span class="cust-check__title">1</span>
        </label>
    </div>
```

Although the visible label changes, the underlying names for the inputs do not change after the Label and Admin label are changed.

This impacts when eg making multiple copies of the some survey with slight variation.

Does this have any impact on the platform? If not then we can de-prioritize this bug.

**Comment by cbunicef** [comment]
It's worth noting that when using wagtail-transfer on a survey with incorrect input names in the code, the destination survey has the correct names in the code even though the source survey does not.

**Comment by cbunicef** [comment]
Even after deleting the existing questions from the survey and recreating them, the resulting questions still use the old input names.

**Comment by sheralim012** [comment]
- wagtail generates a "clean name" from the label and it's used to generate HTML tags
- the clean name is generated and stored when the question is created for the first time
- on subsequent edits, clean name isn't updated, for reference see [here](https://github.com/wagtail/wagtail/blob/main/wagtail/contrib/forms/models.py#L134)
- it's intentional behavior and the reason is also explained [here](https://github.com/wagtail/wagtail/issues/8200)
- the reason it works (new/updated clean name) for wagtail-transfer is that on the destination site it's created for the first time
- wagtail uses clean name internally to generate tags and etc and we use it for polls results, and quiz answers validation
- polls results and quiz answers validation don't get affected by this  

hope this clarifies it, let me know if any change is still required

**Comment by cbunicef** [comment]
Is there any possibility to change how the clean name is derived? Would it complicate things significantly to make the clean name either

1. A hash of the original clean name, with a lookup table
2. A random hash

It is a bit undesirable to have content which appears on the page which is

1. User generated
2. Not visible in the Admin Panel
3. Not changeable

This came up originally when a survey on climate used the clean name "did_you_find_this_hiv_information_helpful" because it was based a copy of a survey on HIV information, which had been changed to read "climate". There are possible complications there, including maybe even risks for users in some countries.
