### ISSUE TITLE
Create progressive web app

### ISSUE THREAD

**Issue by ChrisMarsh82** [unicef/iogt#1285]
Allow users to download the web page as a progressive web app. 
users will be able to receive notifications through the app without being on the webpage (internet access still needed)
users will be able to decide how much content they will be able to download to the web app. (offline access)

This should be presented to users as separate options i.e. Offline access and Web app for notifications.

**Comment by ChrisMarsh82** [comment]
This will need to be build as a java script application so will not work with feature phones or Free Basics

**Comment by ChrisMarsh82** [comment]
Can be a separate page install PWA with no content

**Comment by sheralim012** [comment]
Following table lists down possible app types for IoGT site

| App Types                      | Descriptions                                                                                                                                                                                                                                                                                                                                                 |
|--------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Web App                        | - push notifications should work with the internet                                                                                                                                                                                                                                                                                                           |
| PWA                            | - user should be able to download and install the app on devices<br>- the installed app will work only if the internet is available<br>- push notifications should work<br>- push notifications should accumulate without the internet                                                                                                                       |
| PWA + Offline Access           | - user should be able to download (pre-cache) and install the app on devices<br>- the installed app will work with or without internet<br>- push notifications should work with the internet<br>- push notifications should accumulate without the internet                                                                                                  |
| PWA + On Demand Offline Access | - user should be able to download and install the app on devices<br>- the installed app will work if the internet is available<br>- user should be able to download pages on-demand<br>  - these pages should work without the internet<br>- push notifications should work with the internet<br>- push notifications should accumulate without the internet |

Following table lists down possible transitions for different app types (read it from left to top not vice versa)

|                                           | Web App | PWA | PWA + Offline Access | PWA + On Demand Offline Access |
|--------------------------------|---------|-----|----------------------|--------------------------------|
| Web App                        | -       | yes | yes                  | yes                            |
| PWA                            | no      | -   | yes                  | yes                            |
| PWA + Offline Access           | no      | no  | -                    | no                             |
| PWA + On Demand Offline Access | no      | no  | yes                  | -                              |

@ChrisMarsh82 could you take a look at it to verify if I missed something or if anything needs to be changed

once we decide on it then we'll proceed with implementation details

**Comment by sheralim012** [comment]
I believe we can reduce/combine the following cases 
- Single Page On-Demand Offline Access
- Multi Page On-Demand Offline Access
- Full Offline Access

into a single case
- Let's say there is a download button on a page (customizable wagtail component)
- Clicking the download button will initiate the caching
- That page and all the descendants (not referenced pages) of it will be included in caching

Reduced Cases
Single Page caching would be like clicking the download button on an article
Multi Page caching will be like clicking the download button on a section
Full Offline caching access will be like clicking the download button on the homepage (only a single locale could be downloaded at a time)

@ChrisMarsh82 I have outlined it as we discussed, let me know if you have any questions

**Comment by cbunicef** [comment]
Thanks @sheralim012 for this suggestion. In some cases this would be neat and tidy, but we need to assume that our users:

- May be on slow networks, so downloading may take a lot of time
- May need to be very careful with their data usage if they are paying, so downloading may be expensive
- May have less space on their devices, so downloading may limit the other things they can do with their device
- May have lower levels of tech literacy, so they may not fully understand the implications of downloading

For these reasons we need to have the ability to add explanatory information when users are making the choice to download. We wouldn't want to show this explanatory info on every load of a Page, including to users that don't have an interest in downloading the content for offline viewing.

In your proposal above we could create an article with a customizable Wagtail component (I'm assuming this would work like a content block), but then we would need to place all content _underneath_ that article with that download button content block, rather than underneath a section as we most often do.

What is the part of the current approach that isn't working? The approach that we've discussed is:

- Separate Page type for offline access, which can be linked to from other Pages on the site
- That Page type can include a Paragraph content block, and also the Wagtail component/content block which initiates downloading
- In the Wagtail component the Admin selects the Manifest that should be used for the download
- That Manifest defines the scope, ie the base URL under which content will be downloaded

Is the Manifest and the scope where we're having problems? Or something else? If you can share specifics then we can try to figure out a way to also meet the goals around properly informing the users.

**Comment by cbunicef** [comment]
@sheralim012 I'm realizing that your solution and my solution are very similar, the only thing missing from your solution is that the Admin can define the base URL.

Is that possible to add? There is no immediate need for that to be defined in the Manifest.
