### ISSUE TITLE
Clarification of Comment Moderation Features

### ISSUE THREAD

**Issue by lenkada** [unicef/iogt#1404]
**Comment Moderation includes the following buttons - Unpublish / Hide / Validate:**

![image](https://user-images.githubusercontent.com/113142748/189760606-8180342d-8dcb-4c7c-be13-43211d85e176.png)

**Unpublish**:  Not meant to be on the site.  A final assessment.
**Hidden**:  Meant to be on the site but hidden.  More of a transient assessment.

In future perhaps we have: 
1.  Offices could set up configurations so that every new comment is hidden and then comments can be manually shown.  
2.  If AI moderation flags something it is hidden and this is reviewed by users and then it can be shown.

**Validate** should instead be Approve - so someone has approved this content.  It shouldn't be also used to confirm the unpublish/hide actions - but rather it's more that you have approved said comment to be shown on the site. 

To further clarify, you have a comment that is new:
a) it ends up in the queue 
b) it’s an ok comment it can be shown on the site (you don’t want to unpublish and you don’t want to hide it),
c) you don't want it to leave the queue as it’s fine to be shown, 
So then you hit Approve and it is then removed from the queue and it continues to appear on the site and is no longer in the queue.

**Once an action is taken on any comment it should get taken out of the comment moderation process/list.  Whatever button is chosen (unpublish / hide / approve) it would then remove itself from the list.  So you don't need to hit unpublish and then approve or hide and approve.**

The following actions need to take place (@sheralim012 for your action please):
1.  Change Validate (name) to Approve.
2.  Ensure that the buttons act so that - whatever button is chosen (unpublish / hide / approve) the comment would then remove itself from the list. 

@cbunicef Having pondered over this even further, a comment can be unpublished and it is banished forever (following on from that, removed from the comment moderator's "list").  If a moderator chooses to "hide" a comment which is not so definite - with this new instruction then after clicking hide it would be again removed from the list.  But at a later date, the moderator might want to filter for comments that they have previously hidden and decide indeed it may be appropriate to show that earlier hidden comment.  Is this the correct distinction then for unpublish and hide?  

Are there more concrete examples of unpublish/hide?  Unpublish would be a comment that includes profanity (that may have been overseen by AI moderation for whatever reason).  What however would be a good example of a comment that requires hiding?

**Comment by cbunicef** [comment]
Thanks very much for this @lenkada. I made a small fix to the above: "c) you **_don't_** want it to leave the queue as it’s fine to be shown,"

Re your question

Unpublish is a definitive moderation on the comment - this should not be shown on the site.
Hide is a temporary moderation on the comment - I suspect that this should not be shown on the site.

The AI always makes a temporary moderation, ie "hide". In the future, the Admin can set the platform to always make an initial temporary moderation of "hide".

A community moderator can choose Unpublish if they feel the comment clearly should not be shown on the site, for example it is spam or abusive.

A community moderator can choose Hide if they *think* the comment should not be shown on the site.

Ideally hidden comments are periodically reviewed and either approved or unpublished by administrators, so that there are no hidden comments on the site. This may not always happen.
