### ISSUE TITLE
Content Import Tool is Down

### ISSUE THREAD

**Issue by lauriemarkle** [unicef/iogt#1447]
When navigating to the content import tool on any IoGT site, when "Choose Page" is selected, the administrator receives a "Forbidden" error message. 

<img width="1122" alt="image" src="https://user-images.githubusercontent.com/74552270/198720694-d26c59fb-339c-4873-8de2-827cdfc29c7e.png">

**Comment by istride** [comment]
I have checked the wagtail-transfer configuration and all seems ok there.

The global site has been upgraded recently to the latest version of IoGT (v2.1.0). I have rolled back to the previous version (v2.0.23), after which, the problem disappeared. This suggests that there is something about the latest release that is causing wagtail-transfer not to work. There are no errors (or stacktraces) in the logs.

I will keep the global site on the v2.0.23 while the issue is being fixed.

@ChrisMarsh82 I think this requires urgent attention.
