### ISSUE TITLE
400 error when adding a radio field to a long survey - possibly due to too many fields?

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#1509]
We are receiving a 400 error when adding another radio type field to this survey: https://rw.goodinternet.org/admin/pages/828/edit/

Adding a single-line type field works fine. Copying the survey to a new Page and then adding a radio field also gives a 400 error.

**Comment by sheralim012** [comment]
You are right, there were too many (more than 1000) HTML form fields in the survey submission. This is a Django security feature to handle suspicious activity see [here](https://docs.djangoproject.com/en/3.2/ref/settings/#data-upload-max-number-fields)

**Comment by cbunicef** [comment]
Let's set the limit to 3000, unless you have reservations. The survey the admin was creating is very long, I don't think we'll pass 3x that length.

I'm assuming it's clear from the server logs what caused the exception and how to resolve it.

**Comment by istride** [comment]
I would rather keep the default value unchanged and make the setting configurable at runtime, so that it can be increased temporarily or only for certain deployments. I would see this as a temporary fix for what seems like a problem of bad design.

My understanding is that this problem only affects the admin/editing side of a survey, so it would be better to intervene there rather than compromise security everywhere. Is it worth looking into how we might break up the questionnaire editing interface to keep within the 1000 input field default limit?
