### ISSUE TITLE
Community Comment Moderation permission setting changed in 2.15.6

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#1521]
I noticed that in 2.15.6 our permissions for Comment Moderation looks different:

 ![image](https://user-images.githubusercontent.com/30042226/215089272-a295a267-a490-4cbd-ba57-155e65d19589.png)

Is the “Can moderate comments” setting now for the user-side comment moderation? And what does the “can view” setting mean here?

Is there a way we can make this more clear, eg separating the Admin Panel comment moderating from the Community Comment Moderation again? (I think this is how it was pre 2.15.6) It would also be helpful to explain "Can view" more clearly.

**Comment by sheralim012** [comment]
Yes, "Can moderate comments" permission is restricting access to user-side comment moderation.

Each model has 4 [default](https://docs.djangoproject.com/en/4.1/topics/auth/default/#default-permissions) permissions (view, add, change, delete) tied to it. If a model is registered on Wagtail/Django admin panel then these permissions can limit user access to perform actions.

“Can view” permission means that the user can view records of the model on the Wagtail/Django admin panel.

We are using 3rd party [package](https://django-comments-xtd.readthedocs.io/en/latest/) for comments and it has an additional custom permission “Can moderate comments” tied with model “Comment” and that’s why Wagtail is showing it against “Comment”. Community comment moderation access is also controlled via this permission.

We can create (new) custom permission for comment moderation and use that instead. We will also have to hide existing “Can moderate comments” permission as well. Something like this
<img width="849" alt="Screenshot 2023-02-08 at 2 45 29 PM" src="https://user-images.githubusercontent.com/49383675/217495091-592c34a8-812e-4d49-bf59-aacd602a5c35.png">

Maybe we can add help text to explain permissions or add a link to some readme as well.

Let me know if this makes sense or I missed something.

**Comment by cbunicef** [comment]
Let me check, you are saying:

- Our Admin Panel comment moderation permissions are part of model "Comment" and are "view", "add", "change", "delete"
- The Community Comment Moderation permissions are part of model "Comment" and are "Can moderate comments"

You're proposing changing Community Comment Moderation permissions to be in a model named "Comment moderation" with the permission option "Can moderate comments".

If that understanding is correct then I agree, but let's call the new model "Community comment moderation" with permission "Can moderate comments"

**Comment by cbunicef** [comment]
Here are the user stories I mentioned on the call:

As an ADMIN, I am used to Groups permissions being ONLY for users who can access the Admin Panel.

As an ADMIN, I am used to managing permissions of non-Admin users at Page level, in the Settings tab.

As an ADMIN, I am not necessarily very familiar with permissions, and I may not know about "Can access Wagtail Admin" permission.

As an ADMIN, I may think about permissions in a binary way - can someone access all the functions I can in Wagtail Admin, or are they a public site user? (for someone who uses many systems, but not at Administrator level, this is how systems may generally appear to work)

As an ADMIN, I would like a clear demarcation between permissions that I can safely give non-Admin users and those I should only give to Admin users. Today it seems clear that any permission in Group settings should only be given to Admins. If non-Admin user permissions are introduced into Group settings, it should be very clear that they are meant for non-Admin users.

As an ADMIN, if I give a user Admin Panel access for the first time, I would like in that moment to be able to consider the full implications of that access. If a user was (correctly) added to Groups previously without my knowledge, I don't want those Group memberships to give them access in Admin Panel in a way that I don't expect.

---------------------------

All this leads up to - 

It may not be a best practice from a standpoint of organizing data or permissions, but from a perspective of meeting Admins' expectations I think we should completely separate permissions which give access within the Admin Panel and those which gives access within the public facing side of the site.

This is already done with Page level permissions. Permission to "view" a Page on the public site doesn't give me permission to navigate to that Page in the Admin Panel.

Here is what I would suggest for Community Comment Moderation specifically:

Listed in the Groups permission as "Community Comment Moderation"
Two check boxes, "Can moderate comments on public site" "Can moderate comments in Admin Panel (requires Admin Panel access)"

Is this possible @sheralim012 ?

**Comment by cbunicef** [comment]
Per our discussion, here is the wiki entry: https://github.com/unicef/iogt/wiki/Structuring-User-Groups-Permissions-to-Accommodate-User-Facing-Site-Permissions

**Comment by istride** [comment]
> So if someone has the general "Community comment moderation > Can moderate comments" permission you're suggesting and then they are given Admin Panel permission

@cbunicef I missed this point yesterday. I'm suggesting that "community comment moderation" exclusively refers to comment moderation that happens via the public-facing user interface by registered users who do not have access to the admin interface. As such, it should not be conflated with how admins moderate comments, which I think is what is continuing to happen in this PR.

In my view, an admin should moderate comments by manipulating them directly via the admin interface. There should be no advantage given to admins by having access to "community comment moderation" - except to gain access to the public interface, which should be unnecessary.

To clarify my earlier suggestion, I think there should just be two options with regard to comment moderation:

- Comment
  - Can moderate (via admin interface)
- Community comment moderation
  - Can moderate (via public interface)

The situation is awkward because in order to do community comment moderation a user needs to be able to change two different models ('comment' and 'moderation'), whereas an admin only needs to change the comment, and this doesn't fit neatly into Django's standard permissions model (view, add, change, delete). However, the 'community moderation' model is the entry point for community moderation and the comment model is the entry point for admin moderation and that is why I think the permissions structure above is more appropriate.

Do you agree with this suggestion?

**Comment by cbunicef** [comment]
This is different than my understanding of how the permissions worked based on the earlier conversations, so that may by why we haven't been on the same page.

I think your two options will be easy for users to understand:

> * Comment
>   
>   * Can moderate (via admin interface)
> * Community comment moderation
>   
>   * Can moderate (via public interface)

I just want to make sure that
- an Admin ONLY needs to have "Can moderate (via admin interface)" access all the data and functions they need for all comment moderation actions including actions related to the community comment moderation 
- a user ONLY needs to have "Can moderate (via public interface)" to access all the data and functions they need for moderating from the front-end
- a user can be given EITHER or BOTH
  - the ability to moderate comments via the comment queue
  - the ability to respond to comments on the user side as a "Moderator" (I think we have this ability, if we don't then this can be ignored)

**Comment by istride** [comment]
> the ability to moderate comments via the comment queue

@cbunicef does the "comment queue" mean the admin interface for managing comments?

The 'moderator' label on comments appears if the commenter has the original "Can moderate comments" permission. We would not give community comment moderators this permission because it applies to the admin interface.

Would you like comments by community comment moderators to be labelled 'moderator' as well? Should the same label be used, or a different label e.g. 'community moderator'?

**Comment by cbunicef** [comment]
Comment queue is the public side of the site
