### ISSUE TITLE
Add Javascript user activity tracking via Matomo

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#1566]
We can start the process of testing Matomo by adding simple JS tags.

We can consider this Django app: https://github.com/mikbuch/django-matomo

**Comment by istride** [comment]
@cbunicef If we are seeking to do the bare minimum to begin testing Matomo I suggest we avoid adding features like 'local' vs 'global' tracking at this stage. Assuming that more work will be required to track activity without using JavaScript, we will have to revisit this in the future.

What testing do we plan on doing? Perhaps the testing can be done in development or staging (sandbox) environments without requiring new features to be released at this point.

**Comment by istride** [comment]
There is an official way to [send tracking requests to multiple Matomo servers](https://matomo.org/faq/how-to/how-do-i-send-tracking-requests-to-two-or-more-matomo-servers/).

@Alihassanc5 @sheralim012

**Comment by cbunicef** [comment]
> @cbunicef If we are seeking to do the bare minimum to begin testing Matomo I suggest we avoid adding features like 'local' vs 'global' tracking at this stage. Assuming that more work will be required to track activity without using JavaScript, we will have to revisit this in the future.
> 
> What testing do we plan on doing? Perhaps the testing can be done in development or staging (sandbox) environments without requiring new features to be released at this point.

Revisiting in the future is fine. We need to do testing to make sure the counting works well, but since it should work without issue, probably more importantly we need to start working with the COs and the Matomo interface. They need to give feedback so that if in the worst-case scenario they hate it, we will be able to consider another platform.

**Comment by istride** [comment]
A suggestion:

- Create a single site in Matomo that all COs can access with their own Matomo account, e.g. based on global or sandbox.
- Optionally, [Import data from Google Analytics into Matomo][1]
- Optionally, set up Matomo tracking on one site using [django-matomo]

My preference would be to allow this testing to happen without any changes to IoGT, but if we can't do that, I'd rather use the django-matomo app because it can be added and removed easily, without leaving a trace (the current PR requires a DB migration).

[1]: https://matomo.org/faq/general/set-up-google-analytics-import/
[2]: https://github.com/mikbuch/django-matomo

**Comment by cbunicef** [comment]
I see what you're saying. Let's set up some kind of actual tracking on one site to test, either global or sandbox. I don't know if we will be able to get support on importing data, but I will ask.

**Comment by sheralim012** [comment]
@Alihassanc5  Add support for a single matomo site through env. variables instead of local and global in site settings.
