### ISSUE TITLE
Add Meta advertising tag / Matomo Tag manager in Site Settings

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#1651]
One possibility is to add Meta advertising tag now, and Matomo tag manager later
Another possibility is to add Matomo Tag Manager now

Please add this explanatory text to the Site Settings box:

"Currently this feature only works on devices using JavaScript (eg basic featurephones are not supported), and does not work with MNO zero-rating or Meta Free Basics."

**Comment by cbunicef** [comment]
@istride per our convo, thanks

**Comment by istride** [comment]
As previously discussed, I think it is worth integrating Matomo Tag Manager into IoGT because it is very likely to provide additional value in the longer term because it will allow site owners/admins to update tags on their own, without developer intervention. The caveat to that is that a JavaScript-enabled client is required for the Tag Manager to work, so it does not cover all the situations in which IoGT is expected to be used. Additional work would have to be done to extend the Tag Manager so that it would work with clients that do not have JavaScript enabled, and it is understood that this work is not in scope here.

The vast majority of the work required to implement the Meta tag vs Matomo Tag Manager is the same. If the Tag Manager is not usable, the work done could be reused to implement the Meta tag. Since there is a bit of time pressure on this, I think we can push for a release by next Wednesday.

Actual tags will be required for testing, both for Tag Manager and Meta. Please send them across privately i.e. not via this issue.

**Comment by cbunicef** [comment]
The Meta tag should now be in place, but I'm not seeing anything when accessing the site.

![image](https://github.com/unicef/iogt/assets/30042226/dd4f980d-3a18-4a24-8fb8-ff2e4a3cfe90)

I see this error in Dev Tools

![image](https://github.com/unicef/iogt/assets/30042226/9595995a-564a-4ef4-9dd6-43797c0109a5)

Possibly we need to implement the Matomo Container Tag differently to be CSP compatible?

https://matomo.org/faq/general/faq_20904/

**Comment by istride** [comment]
The CSP would have to change to accommodate the scripts that might be loaded via Tag Manager. In this case, the Meta tag needs to be allowed to load. I have made changes to the sandbox that should allow just the Meta tag to work - following [Meta's recommendation](https://developers.facebook.com/docs/meta-pixel/advanced/#content-security-policy). After the change, I still see the CSP blocking the loading of a resource at "www.facebook.com", but it is likely that merely sending the request is sufficient, so it shouldn't be a problem.

There is a more general way to allow any tag loaded through Tag Manager to work, but it requires us to set the CSP in the IoGT app instead of in the Nginx proxy, as it is currently.

I think we can ignore the errors related to unisitetracker because we should be proxying those anyway. These errors are probably related to the default Matomo tag that is automatically set up in Tag Manager - which I thought would be removed.

In any case, let me know if the Meta tag is working now.

**Comment by cbunicef** [comment]
There was a misconfigure of a Matomo tag within the Container Tag - I removed it and we should no longer be getting the unisitetracker CSP error

Meta is still not working unfortunately. I think you should be able to accurately check the Meta tag using "Meta Pixel Helper" Chrome plugin https://developers.facebook.com/docs/meta-pixel/support/pixel-helper/

**Comment by istride** [comment]
The documentation is not complete because the tag requires access to 'www.facebook.com' as well. It should be working now.
