### ISSUE TITLE
MoyaPay report

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#1655]
I had a look at the db and I think the answer is pretty straightforward. The table comments_commentmoderation has three fields

id - index
state - moderation action
comment_id - comment the action was applied to

I didn't see any other table that looked like it included moderation actions.

What we would additionally need here is 1) date of the action 2) user id of the user who took the action

With that info available we should be able to make the report which explains which day which user completed a comment moderation action.

**Comment by istride** [comment]
The approach I have taken on this is to introduce a new database table that logs every moderation action performed by community moderators. Each log entry has the following fields:

- action: name of the moderation action taken e.g. 'approved', 'rejected', etc
- created: time the action was taken
- comment: comment the action was performed on
- moderator: the user who took the action

This was preferred over adding fields to the existing moderation table because the existing table only records the latest state and therefore does not keep a history of actions taken, which is important for reporting purposes. It is my opinion that there is likely to be fewer issues with a new table versus modifying the existing one.
