### ISSUE TITLE
Import brings in a previous title field than the current

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#1681]
This Page

https://admin-demo.iogt.site/admin/pages/3509/edit/

was imported from this page

https://www.internetofgoodthings.org/admin/pages/3262/edit/

When the import finished the Page title on the destination site was "Behavioural and Social Drivers (BeSD) of HPV Vaccination Survey (U-Report Version)" - however that is an old title which had been changed on the source site.

**Comment by cbunicef** [comment]
@istride Possibly this is an impact from upgrades?

**Comment by istride** [comment]
It looks to me as though the article was copied on internetofgoodthings.org with the original title ("Behavioural and Social Drivers..."), then edits were made, including to change the title, but the article was not published afterwards. The import into "admin-demo" seems to be of the most recently published version, which is the version that was current at the time of copying.

It's most likely that this is intended behaviour rather than a bug introduced through the latest upgrade to Wagtail.

**Comment by cbunicef** [comment]
Thanks, I agree this is the desired behavior. I thought I considered that there might be a draft, but I guess I mistook it.
