### ISSUE TITLE
Investigate RapidPro integration

### ISSUE THREAD

**Issue by isedwards** [unicef/iogt#24]

**Comment by dannyparsons** [comment]
@geoo89 here is the issue on RapidPro which you may work on.

**Comment by geoo89** [comment]
Updates after some discussions with David:

RapidPro implements various [channel handlers](https://github.com/nyaruka/courier/tree/main/handlers) (e.g. for Telegram, WhatsApp, Firebase) to communicate with different services. Communication is done via HTTP requests, with a fixed URL for most (all?) services (e.g. https://api.telegram.org for Telegram). This means we cannot directly communicate between RapidPro and the IoGT website using an existing channel handler, but adding a new one to RapidPro would likely take too long to propagate to the installations of RapidPro that are in use within UNICEF. Thus in the interim we will have to use an intermediate service which relays messages between the IoGT and RapidPro servers; here Firebase offers itself as we will have full control over how the relaying is done.

On the front-end side, we agreed that it makes sense to go ahead with [Pinax messages](https://github.com/pinax/pinax-messages). It offers a clean, simple implementation without external dependencies. (See [templates](https://templates.pinaxproject.com/messages/threads/1/) for what it roughly looks like.)  
Pinax-messages defines [models](https://github.com/pinax/pinax-messages/blob/d755f088174d69a31ae2fcb8527735e0614c2d70/pinax/messages/models.py) for messages and message threads, and allows to plug in an existing user model. (Which also means that messages are stored server-side, and thus it should only be used for non-sensitive communication for the time being.)
As it is rather simple, rather than installing the package, it makes more sense to take its source so that we can expand upon it (e.g. communication with bots rather than other users, message attachments, quick replies).

I'll start trying to get pinax-messages to work as an app within IoGT, and we can go from there.

**Comment by geoo89** [comment]
https://github.com/unicef/iogt/issues/24

**Comment by geoo89** [comment]
https://github.com/unicef/iogt/pull/116

**Comment by geoo89** [comment]
Initial investigation succeeded by implementation Epic, see Issue #121
