### ISSUE TITLE
Behavior for pages not available in all languages

### ISSUE THREAD

**Issue by geoo89** [unicef/iogt#372]
For a given page, the language select dropdown only offers the languages that this article is available in.

If a user lands on a page in a language they don't speak, they might want to change the language so they can navigate the page.
Should we consider this case and instead of not offering all languages, rather redirect to the home in the language of choice, or a page indicating that this article doesn't exist in the language of choice?

**Comment by dannyparsons** [comment]
I agree the dropdown should always show all available languages.

If the current page isn't available in the newly selected language then I suggest redirecting to the home page.

**Comment by cbunicef** [comment]
I would prefer to have a page informing that there is no content in this language, because I would always like users to have an expectation of where they will end up after making a navigation choice.

If we send them to the content when there is content, or the homepage when there is no content, then they don't know what will happen when they click the language drop-down.

On the "no content" page we could use best practices for a 404 page. The text could read eg:

"Sorry, '[page title]' is not available in [language]. If you want to keep browsing in [langauge] you can click here to return the homepage."

**Comment by geoo89** [comment]
The challenge with a custom page is that we don't have localized strings for this.

The current implementation, meaning that only languages for which an articles is available show up in the dropdown, seems to be the best solution right now, until we have translated strings for this?

**Comment by ehmadzubair** [comment]
Go with the options @geoo89 has mentioned for now

**Comment by geoo89** [comment]
Remark: This is a temporary solution unless we have dedicated page to indicate that the page is not available in the language of choice.
