### ISSUE TITLE
URGENT: Section name not visible when viewing section

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#414]
http://central.iogt.site/en/sections/your-health/mental-health/

![image](https://user-images.githubusercontent.com/30042226/128269872-c794263b-db6a-4c00-8f66-e2084d01d3c7.png)

**Comment by sheralim012** [comment]
@ehmadzubair

**Comment by geoo89** [comment]
If a lead image is present, should the section title appear above, below, or overlaid over the image?
In case of the latter, I assume it'd be necessary to also specify a font color in the CMS for that particular overlay, as a good choice depends on the specific image?

**Comment by ehmadzubair** [comment]
@geoo89 should I add the font color to the admin too?

**Comment by geoo89** [comment]
I'd say yes but let wait for @cbunicef to confirm.

**Comment by ChrisMarsh82** [comment]
Add title above image.

**Comment by geoo89** [comment]
For reference, this is what it looks like in v1:
![image](https://user-images.githubusercontent.com/678199/128677621-67a5b90b-5faa-4377-a94d-e12cc18ac958.png)

**Comment by geoo89** [comment]
Text is now overlaid over the image in white if an image is present, otherwise appears in black.
![image](https://user-images.githubusercontent.com/678199/128881957-960a9cd8-b292-494f-a1d4-916781fd7d78.png)
![image](https://user-images.githubusercontent.com/678199/128881993-bd501ff2-8cbf-4646-a783-a97d9c3a479f.png)

Leaving this open in case we still want to change this by e.g. giving the option to specify a color, or always putting the text above the image.

**Comment by geoo89** [comment]
Fixed in 19db98191aeeaaa4bcc7637dd0f1ccaffb5a5c59 by putting the title below the image.
