### ISSUE TITLE
Use Wagtail 2.11.x (Long Term Support release)

### ISSUE THREAD

**Issue by isedwards** [unicef/iogt#46]
Modify the wagtail version in `requirements.txt` to use the [Wagtail Long Term Support (LTS)](https://github.com/wagtail/wagtail/wiki/Release-schedule) release.

This is a minor code change, but it requires all developers to delete their local test database `db.sqlite3` (so that Wagtail migrations can only be applied up to the LTS release) - and also update or delete their virtual environment.

The new requirement should be:
`wagtail==2.11.*`

**Comment by istride** [comment]
I think that we ought to do this sooner rather than later to avoid unintentionally relying on a feature or third-party app that isn't supported by, or backwards-compatible with the LTS release. Any upheaval is only likely to be worse the later we leave this.

@isedwards any objection to doing this now, before anything else?

**Comment by isedwards** [comment]
Agreed. We should all delete our local development databases and run `migrate` and `createsuperuser` again when this is merged.

In #50 we should probably change
`wagtailmenus>=3.0.2` to `wagtailmenus~=3.0` to make sure that a future breaking change in `wagtailmenus` doesn't accidentally get rolled out to production (we're seeing this a lot with the current IoGT site).

See [PEP440 compatible release](https://www.python.org/dev/peps/pep-0440/#compatible-release)

**Comment by isedwards** [comment]
@istride could you also remove Django from our `requirements.txt` (wagtail will manage this dependency including the required version)?
