### ISSUE TITLE
Section X contains link to Section X in some responsive sizes

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#570]
![image](https://user-images.githubusercontent.com/30042226/133601957-e367803e-d4b9-4bd0-a601-d378a5acd547.png)

URL: http://34.122.27.221/en/sections/emergency-information/about-covid-19/

The highlighted link points to http://34.122.27.221/en/sections/emergency-information/about-covid-19/

Visible in widths 768, 1024

**Comment by geoo89** [comment]
I believe this is an instance of this issue: https://github.com/unicef/iogt/issues/370
Rather than the section name appearing in the section, it's the flat menu which appear there when it shouldn't.

It only happens in desktop view, but not in mobile (single column) view. @azahid89 is working on fixing this.

**Comment by geoo89** [comment]
Fixed by #574
