### ISSUE TITLE
Logo and image scaling issues

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#609]
1024 and above width: logo is clear and article image is clear
![image](https://user-images.githubusercontent.com/30042226/136183185-186e5247-9636-49ac-8dba-c6413b590f4e.png)

768 to 320 width: logo is pixelated and article image is clear
![image](https://user-images.githubusercontent.com/30042226/136183379-6533a9af-8f44-4f5e-b83a-1be17b07ff20.png)

320 width: logo is pixelated and article image is pixelated
![image](https://user-images.githubusercontent.com/30042226/136184125-8277bafb-9ec5-484f-adf6-3006bd207e51.png)

I'm noticing that the logo is stored as a 60px width image, even though it's always displayed wider than 60px.

**Comment by geoo89** [comment]
For the IoGT logo, serve it at 120px rather than 60.

Ensure only one size per image is loaded (this should already be the case).

For bandwidth reduction: Serve full width images (top) as they are right now, but images that are displayed at half (or less) width (bottom) in a lower quality:
![image](https://user-images.githubusercontent.com/678199/145836365-b6564726-9d0a-4eb1-bceb-a55e861aa892.png)

**Comment by geoo89** [comment]
360 px full width / 180 px half width.
This will look bad on desktop, see #1030
