### ISSUE TITLE
During migration, untranslated pages are migrated to translated language sections, and remain in original language

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#623]
Girl's Zone page and sub-pages are visible in V2, in English, in the Arabic language section:

![image](https://user-images.githubusercontent.com/30042226/136394373-5bd73510-a4b1-4682-af48-ea8f83547876.png)

In V1 Girl's Zone is not translated into Arabic:

![image](https://user-images.githubusercontent.com/30042226/136394601-a3d671e6-57e7-402f-a2ce-9a52344467c8.png)

**Comment by geoo89** [comment]
I believe this is because these sections have children (or descendants) which do have an Arabic translation.
End Violence is another instance of this, with the difference being that some of the descendants are live: https://www.internetofgoodthings.org/section/connect-smart/end-violence/ (Though I'm not sure you can navigate to this page from the homepage)

In V2, each language has its own page tree, and pages cannot live in a language if their ancestor sections don't exist in the given language. So if we drop these sections, we also have to drop these child pages.
