### ISSUE TITLE
Determine if there should be support for child pages of Articles

### ISSUE THREAD

**Issue by ehmadzubair** [unicef/iogt#772]
In V1 content, there are some cases where articles have other pages (articles, questionnaires) as children. While in V2, there is no way to show children of Articles on the frontend. 

Need to determine 2 things:
- Should we allow editors to add children to articles?
- How do we display children of articles that have been migrated already

**Comment by cbunicef** [comment]
There was had a lengthy discussion about this at some point, with David and possibly Danny and me.

I don't remember all the details that were discussed...

I have been using Pages as children of an Article when I don't want a piece of content to show up in the Section. For example there is a poll which will be embedded in an Article and I don't want it to also be listed in the Section.

I think there are valid use-cases for multiple Page-types that can only be navigated to through an Article page:

1. Poll/survey/quiz which only makes sense in the context of the article
2. In-depth further information relevant to an Article that shouldn't be part of paging through the Pages in a Section using "Next"
3. Using an Article as an alternative format to a Section - allowing free-form designing of how child content is navigated, rather than the prescriptive Section format

I'll add that I have seen content developers organically organizing their content in a hierarchy which includes children of Articles.

I main argument against I remember is that these child Pages won't be automatically listed in the Section and that may be confusing for beginners learning the CMS. But it would be useful to ask David and/or Danny if they remember more.

**Comment by geoo89** [comment]
I had a discussion with David, and we concluded that given the use cases you mentioned, probably the most sensible solution at this point is to keep supporting articles with children in V2. That also means that we don't have to implement anything special for the migration here.

If you agree, feel free to close this issue.
