### ISSUE TITLE
shortcut icon is resized too small and stretched

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#789]
V2 above vs V1 below

![image](https://user-images.githubusercontent.com/30042226/141092936-abeec813-7ed6-4101-ac90-b9e7f3087233.png)

V1 site: https://rke-iogt.unicef.io/
V2 site: http://iogt-global-showcase.idems.international/en/

**Comment by geoo89** [comment]
Is this referring to the favicon, or some other icon? The favicon can be specified in the site settings.

**Comment by cbunicef** [comment]
Yes favicon, in the HTML I see it referred to as 

`<link rel="shortcut icon" href="/static/favicon/favicon.ico">`

**Comment by geoo89** [comment]
This href should point to the customizable favicon from the CMS rather than a static file.

**Comment by geoo89** [comment]
Can you point me to the site where you found this?
On iogt-global-showcase, I see `<link rel="shortcut icon" type="image/jpg" href="/media/images/favicons.original.width-60.png"/>`, i.e. a custom icon is used.

**Comment by cbunicef** [comment]
The custom icon is the favicon that was resized during the migration. Maybe that resize is fixed now?

**Comment by geoo89** [comment]
The favicon is customizable, and we set the default icon to 32x32 rather than 16x16.

Now this seems to look good also in the shortcut icon.

Before (16x16): 
![image](https://user-images.githubusercontent.com/678199/145276876-61e6d1f8-c4b4-449a-952d-dec91f1154f6.png)

Now (32x32):
![image](https://user-images.githubusercontent.com/678199/145276908-8c845e2b-6be5-46dd-8910-c468c8917178.png)
