### ISSUE TITLE
During migration, Page history is lost

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#841]
Do we have any way to retain this? 

It would be useful to understand, especially, when content was "Last Updated". No need to go into the Revisions tool from V1, I don't think it works.

**Comment by geoo89** [comment]
Could you clarify? I thought we agreed not to migrate the revision history?

Regarding "Last Updated", I assume you're referring to this column which is currently blank?
![](https://user-images.githubusercontent.com/678199/144023882-f6296ac9-631e-4d3b-9722-b2faedb1b9ca.png)
We updated the migration now to contain this information. Let me know if this is sufficient.
Just in case there's anything else we can derive from it, we're also _storing_ the V1 revision history now, but this has no visible effect because in V2 history is done differently, as far as I understand.

**Comment by cbunicef** [comment]
Thanks @geoo89. Yes the last updated column is what's most important, so platform admins can see how old the content is. 

If we could also get the user account included on the History that would be ideal.

Storing the revision history is fine, but I don't anticipate it being used.

**Comment by geoo89** [comment]
> If we could also get the user account included on the History that would be ideal.

Are you referring to #846, or do you mean we should store it as part of the V1 revision history (which we are likely not going to use)?

**Comment by geoo89** [comment]
Resolution: We would like to populate our page history at least with the time stamp and user who made the last change. The full history is not needed.

**Comment by geoo89** [comment]
There's a simple way of adding the user information in a similar vein to the last_updated timestamp:
![image](https://user-images.githubusercontent.com/678199/144390846-bbde7fe7-2949-438b-a972-e3b25b0c4b27.png)

Just like the last_updated timestamp, this data will get overwritten once you edit and save a page though.

Is this sufficient, or would you still prefer to have proper history entry (which will be trickier)? We had some internal discussions and there are some concerns adding an admin panel that allows to run management commands (e.g. update the history with V1 information) as it is too delicate an operation. In particular it'd be safer to make a backup before running these, and also the management commands may only work during a limited time frame (if e.g. we change some database schema later). So it'd be better to get as many of these tasks out of the way before the migration, and use management commands only if absolutely necessary, by invoking them manually on the deployment side.
@cbunicef

**Comment by cbunicef** [comment]
Please take the simple approach and retain the data in a separate database as discussed previously.
