### ISSUE TITLE
The ability to export survey/poll/quiz data by user profile

### ISSUE THREAD

**Issue by ChrisMarsh82** [unicef/iogt#860]
Linked to #520

**Comment by cbunicef** [comment]
Please consider #599 when building output.

**Comment by cbunicef** [comment]
@ChrisMarsh82 we have discussed this on calls, but to be specific on the user stories here:

As a DATA ANALYST I need to be able to download, with one action, all Form Data for a particular user.

As a DATA ANALYST I would like to be able to download all of a user's Form Data, but select which Forms to include - this is optional.

As a DATA ANALYST I need a variables in the exported data which indicate 1) the survey's name 2) the survey's URL 3) the survey's Page number (plus anything else? no ideas at this moment)

As a DATA ANALYST I would like the **option** to output the dataset as long-format rather than wide-format, ie

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/cbrooks/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/cbrooks/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
</head>

<body link="#0563C1" vlink="#954F72">



Survey Name | Submission Date | Field | Response
-- | -- | -- | --
Survey 1 | 2022-06-28 | User | User   1
Survey   1 | 2022-06-28 | Q1 | Answer 1
Survey 1 | 2022-06-28 | Q2 | Answer   1
Survey   1 | 2022-06-28 | Q3 | Answer 1
Survey 1 | 2022-06-29 | User | User   1
Survey   1 | 2022-06-29 | Q1 | Answer 1
Survey 1 | 2022-06-29 | Q2 | Answer   1
Survey   1 | 2022-06-29 | Q3 | Answer 1
Survey 2 | 2022-06-30 | User | User   1
Survey   2 | 2022-06-30 | Q1 | Answer 1



</body>

</html>

rather than

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/cbrooks/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/cbrooks/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
</head>

<body link="#0563C1" vlink="#954F72">



Survey Name | Submission Date | Survey 1.Q1 | Survey 1.Q2 | Survey 1.Q3 | Survey 2.Q1
-- | -- | -- | -- | -- | --
Survey 1 | User 1 | Answer 1 | Answer 1 | Answer 1 |  
Survey   1 | User 2 | Answer 1 | Answer 1 | Answer 1 |  
Survey 2 | User 1 |   |   |   | Answer   1



</body>

</html>




As an ADMIN I need DATA ANALYSTS to be able to download this data -only- for the Pages they have access to via their Group permissions.
